POST http://localhost:8080/api/v1/agent/run
Content-Type: application/json

{
    "goal": "仿照格林童话的风格，写一个关于勇敢的小兔子冒险的故事，要求情节曲折，有点黑暗。"
}

###
GET http://localhost:8080/health
###
GET http://localhost:8080/api/v1/agent/4e5739f8-8e35-4291-bb86-1568965a627c/stream